[package]
name = "meilisearch2pushover"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.7.4"
flate2 = "1.0.28"
iso8601 = "0.6.1"
pushover-rs = "0.3.15"
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.114"
tokio = { version = "1.36.0", features = ["macros"] }
